#include <opencv2/opencv.hpp>
#include <opencv2/ximgproc/segmentation.hpp>
#include <iostream>

class Searcher{

public:
    Searcher();
    /**
    *  Computes the bounding boxes proposals using selective Search
    *
    * -Param v input image
    * -Return vector of Rect that are the proposals
    */
    std::vector<cv::Rect> segmenter(cv::Mat v);

    /**
    *  Print the proposals rectangles
    *
    * -Param m input image
    * -Param roi vector of Rect representing the bounding box proposals to print in m
    */
    void printProposal(cv::Mat m, std::vector<cv::Rect> roi);

    /**
    *  Computes the bounding boxes proposals using selective Search
    *
    * -Param img input image
    * -Param threshold threshold used by the library method Canny
    * -Return vector of Rect that are the proposals generated by the edge detector
    */
    std::vector<cv::Rect> edgeExtractor(cv::Mat img, int threshold);

};
